# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f2ccc8c51ca1893d8a6cf590900fa8182f675122a5933b1b5c23302eb6a9ba317ff31c60519bdd4113139a3b0489e9aa3e173ae48424d4912378889113c5566

test:
  secret_key_base: e7825d60643f9088abbe8b809adc551ab2ff318af6a44a03c28d4aeb1cdc61965b869e58e15855ea5cb98f532aca10e7a15b57c7bd9b5c0c9504bcbd38978d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
